[package]
name = "interrupts"
version = "0.1.0"
authors = ["The intermezzOS team"]

[dependencies]
x86 = "0.8.1"

[dependencies.spin]
version = "0.4.4"
default-features = false

[dependencies.pic]
path = "../pic"
